name: Build and Deploy to EKS
on:
  push:
    paths:
      - 'count-users-dir/site/**'
      - 'count-users-dir/Dockerfile'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mendelsh/count-users
      IMAGE_TAG: ${{ github.run_number }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Build static Go binary
        run: |
          cd count-users-dir
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o count-users count-users.go

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./count-users-dir
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Update image tag in Helm values.yaml
        run: |
          # Update values.yaml image.tag
          sed -i "s|tag:.*|tag: \"$IMAGE_TAG\"|" ./count-users-dir/values.yaml

      - name: Commit and push updated values.yaml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./count-users-dir/values.yaml
          git commit -m "Update image tag to $IMAGE_TAG [skip ci]" || echo "No changes to commit"
          git push