apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: {{ toYaml .Values.pvc.accessModes | nindent 2 }}
  storageClassName: {{ .Values.pvc.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
